server: 
  port: 9111
spring:
  application:
    name: plat-console
  profiles:  
    active: dev
---
custom: 
  session:
    expiredTime: 30 #分钟
  cache:
    base64ImgCache:
      expiredTime: 30 #分钟
    logCache:
      expiredTime: 30 #分钟
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/scm?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: passw0rd
    driver-class-name: com.mysql.jdbc.Driver
    
    #----连接池配置----
    #通常来说，只需要修改initialSize、minIdle、maxActive
    #如果用Oracle，则把poolPreparedStatements配置为true，mysql可以配置为false。分库分表较多的数据库，建议配置为false
    #removeabandoned不建议在生产环境中打开
    druid: 
      #配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      
      #配置获取连接等待超时的时间
      max-wait: 60000
      
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

---
spring:
  profiles: prod